---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/25 21:47
---
add_rules("mode.debug", "mode.release")
add_repositories("musmus-repo https://gitee.com/musmus9405/xmake-repo.git")
add_requires("lua v5.4.3", {configs = {shared = false}})

target("HelloLua")
    set_languages("c99", "cxx17")
    set_kind("static")
    add_packages("lua", { public = true })
    add_includedirs("Src", { public = true })
    add_files("Src/*.cpp")
    add_headerfiles("Src/*.h")

target("HelloLuaTest")
    set_languages("c99", "cxx17")
    set_default(true)
    add_deps("HelloLua")
    set_kind("binary")
    add_files("Test/*.cpp")
    add_values("lua", {"$(projectdir)/Test/Lua/"})

    after_build(function(target)
        local folders = target:values("lua")
        for _, folder in ipairs(folders) do
            os.cp(folder, "$(buildir)/$(plat)/$(arch)/$(mode)")
        end
    end)

    if is_plat("windows") then
        add_ldflags("/subsystem:console", "/entry:mainCRTStartup", {force = true})
    end