---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/26 16:08
---

Test.SPrint("test", "tips")
Test.SField = 2
print(Test.SField)
local test = Test.New(2, false)
test:Print("")

function Main(test)
    test:Print("")
    return 20, "ss"
end